packages:
  - turbo
  - docs
  - packages/*
  - examples/*
  - packages/*/tests/fixture/*
  - packages/*/e2e/fixture/*
catalog:
  astro: ^5.10.1
  astro-integration-kit: ~0.18.0
  '@astrojs/compiler': ^2.12.2
  '@astrojs/sitemap': ^3.4.1
  '@astrojs/node': ^9.2.2
  '@astrojs/starlight': ~0.34.4
  '@astrojs/internal-helpers': ^0.6.1
  '@types/content-type': ^1.1.9
  '@types/debug': ^4.1.12
  '@types/hast': ^3.0.4
  '@types/node': ^24.0.7
  '@faker-js/faker': ^9.8.0
  '@lunariajs/core': ^0.1.1
  '@playwright/test': ^1.53.1
  content-type: ^1.0.5
  debug: ^4.4.1
  devalue: ^5.1.1
  sitemap: ^8.0.0
  ast-types: ^0.14.2
  estree-walker: ^3.0.3
  magic-string: ^0.30.17
  nanostores: ^1.0.1
  recast: ^0.23.11
  rehype: ^13.0.2
  upath: ^2.0.1
  tsup: 8.5.0
  typescript: ^5.8.3
  vite: ^7.0.0
  rollup: ^4.44.1
  vitest: ^3.2.4
  '@vitest/ui': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  jest-extended: ^6.0.0
catalogMode: prefer

catalogs:
  lax:
    '@astrojs/starlight': '>=0.29 <0.32'
    astro: ^5
  min:
    astro: ^5
    astro-integration-kit: ~0.17 || ~0.18
    vite: ^4 || ^5 || ^6

onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - sharp

overrides:
  '@croct/sdk': 0.17.0
  astro: 'catalog:'
  picomatch: 3.0.1
  vite: 'catalog:'

patchedDependencies:
  astro: patches/astro.patch
